CREATE TABLE Usuario (
  idUsuarios INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(45),
  email VARCHAR(45),
  password VARCHAR(45),
  token VARCHAR(36),
  isactive BIT NOT NULL,
  created DATETIME,
  modified DATETIME NULL,
  last_login DATETIME NULL,
  CONSTRAINT pk_Usuarios PRIMARY KEY (idUsuarios)
);

CREATE TABLE IF NOT EXISTS Phone (
  idphones INT GENERATED BY DEFAULT AS IDENTITY,
  number VARCHAR(7),
  cytycode VARCHAR(2),
  countrycode VARCHAR(2),
  Usuarios_idUsuarios INT,
  CONSTRAINT pk_phones PRIMARY KEY (idphones, Usuarios_idUsuarios),
  CONSTRAINT fk_phones_Usuarios
    FOREIGN KEY (Usuarios_idUsuarios)
    REFERENCES Usuario (idUsuarios)
);
